export const REVIEW_IMAGES = {
  STUDENT1: './images/landingContent/review/student-1.jpg',
  STUDENT2: './images/landingContent/review/student-2.jpg',
  STUDENT3: './images/landingContent/review/student-3.jpg',
  STUDENT4: './images/landingContent/review/student-4.jpg',
  STUDENT5: './images/landingContent/review/student-5.jpg',
  WORK1: './images/landingContent/review/work-1.png',
  WORK2: './images/landingContent/review/work-2.png',
  WORK3: './images/landingContent/review/work-3.png',
  WORK4: './images/landingContent/review/work-4.png',
  WORK5: './images/landingContent/review/work-5.png',
  WORK6: './images/landingContent/review/work-6.png',
  WORK7: './images/landingContent/review/work-7.png',
  WORK8: './images/landingContent/review/work-8.png',
  WORK9: './images/landingContent/review/work-9.png',
  WORK10: './images/landingContent/review/work-10.png',
  WORK11: './images/landingContent/review/work-11.png',
  WORK12: './images/landingContent/review/work-12.png',
  WORK13: './images/landingContent/review/work-13.jpg',
  WORK14: './images/landingContent/review/work-14.jpg',
  WORK15: './images/landingContent/review/work-15.jpg',
};
